version: '3'
services:
  cooking-admin:
    container_name: cooking-admin
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        DATABASE_CLIENT: ${DATABASE_CLIENT}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PORT: ${DATABASE_PORT}
        JWT_SECRET: ${JWT_SECRET}
        ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - config:/opt/app/config
      - src:/opt/app/src
      - package.json:/opt/package.json
      - yarn.lock:/opt/yarn.lock
      - env:/opt/app/.env
      - public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - cooking-admin
    

networks:
  cooking-admin:
    name: Cooking-admin
    driver: bridge
